name = "LLVMLoopInfo"
uuid = "8b046642-f1f6-4319-8d3c-209ddc03c586"
authors = ["chriselrod <elrodc@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
